# Start with a minimal pipeline that you can customize to build and deploy your code.

# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
  - name: CustomBuildId
    value: $(Build.BuildId)


trigger:
- master

pool:
  vmImage: 'macOS-12'

steps:

- script:
    echo $(CustomBuildId)

- script:
    let cbuildid="$(CustomBuildId) + 30000"

- script:
    echo $cbuildid
    #echo "##vso[task.setvariable variable=CustomBuildId]$cbuildid"

- script:
    echo $(CustomBuildId)
